name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: nodejs20-se-test-app-2025/app # note working directories; using cd didn't work
        run: npm install

      - name: Run tests
        working-directory: nodejs20-se-test-app-2025/app
        run: npm test


# triggered on PR or push (to main)
# runs on ubuntu

# checks code and sets up node.js
# installs dependencies and runs tests
